services:
  app:
    build:
      context: .

    # Interactive mode for CLI application
    stdin_open: true
    tty: true



    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change
        - action: rebuild
          path: ./pyproject.toml

        # Rebuild the image if lockfile changes
        - action: rebuild
          path: ./uv.lock
