[project]
name = "my-app"
version = "0.1.0"
dependencies = ["typer>=0.9.0"]

[project.scripts]
my-app = "my_app.cli:app"

[project.optional-dependencies]
dev = ["pre-commit", "ruff", "pytest"]

[tool.uv]
package = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --tb=short"
