name: "🐛 バグ報告 (Bug Report)"
description: "動作しない、または期待通りに動かない問題の報告"
title: "BUG: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        バグ報告にご協力いただきありがとうございます。
        以下の項目に沿って、可能な限り詳細な情報をご提供ください。
  - type: textarea
    id: summary
    attributes:
      label: "バグの概要 (Summary)"
      description: "バグの内容を明確かつ簡潔に説明してください。"
      placeholder: "例：helloコマンドに特定の文字列を渡すとエラーが発生する。"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "再現手順 (Steps to Reproduce)"
      description: "バグを再現させるための具体的な手順を記述してください。"
      placeholder: |
        1. `docker compose run --rm app my-app hello "test"` を実行する
        2. 次のようなエラーが出力される
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "期待される動作 (Expected Behavior)"
      description: "本来はどうあるべきだったかを明確かつ簡潔に説明してください。"
      placeholder: "`hello test` と表示されるべき。"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "実際の動作 (Actual Behavior)"
      description: "実際に何が起こったか、エラーメッセージなどを貼り付けてください。"
  - type: textarea
    id: environment
    attributes:
      label: "環境 (Environment)"
      description: "問題が発生した環境を教えてください。"
      placeholder: |
        - OS: [例: macOS Sonoma, Windows 11]
        - Dockerバージョン: [例: Docker Desktop 4.29.0]
        - プロジェクトのバージョン/コミットハッシュ:
  - type: textarea
    id: additional-context
    attributes:
      label: "追加情報 (Additional Context)"
      description: "その他、問題に関する追加情報があれば記述してください。"
