name: "🚀 機能要望 (Feature Request)"
description: "新しい機能や改善の提案"
title: "FEAT: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        機能のご提案ありがとうございます！
        以下の項目に沿って、どのような機能が必要か、なぜそれが必要かを教えてください。
  - type: textarea
    id: related-problem
    attributes:
      label: "この機能要望は、何か問題に関連していますか？ (Is your feature request related to a problem?)"
      description: "どのような問題や不便を解決するための機能ですか？"
      placeholder: "例：私はいつも[...]な時に不満を感じます。"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "どのような解決策を望んでいますか？ (Describe the solution you'd like)"
      description: "具体的にどのような機能や振る舞いを期待しているか教えてください。"
      placeholder: "例：[...]ができるようになると嬉しいです。"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "検討した代替案はありますか？ (Describe alternatives you've considered)"
      description: "他に検討した代替案やアプローチがあれば教えてください。"
      placeholder: "例：[...]という方法も考えましたが、[...]という理由で今回の提案の方が良いと思います。"
  - type: textarea
    id: additional-context
    attributes:
      label: "追加情報 (Additional Context)"
      description: "その他、この機能要望に関する文脈やスクリーンショットなどがあれば追記してください。"
